name: Update Readme

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: setup py
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install requests
        run: pip install requests

      - name: run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python ${{ github.workspace }}/stats.py > stats.txt
          cat stats.txt >> profile/README.md

      - name: commit
        run: |
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add profile/README.md
          git add stats.txt
          git commit -m "Update profile/README.md"
          git push